### ISSUE TITLE
Span::is_call_site

### ISSUE THREAD

**Issue by CreepySkeleton** [dtolnay/proc-macro2#190]
Sometimes it's quite useful to have a way to check whether a Span originates on call site or not.

My use case: I'm working on improving error-reporting in a proc-macro. One of these improvements: point to the place where the error originates with. The situation in short: I've got a list of symbols, some of them are generated inside the macro so they are `call_site`, but some of them could be tracked to a certain position in user code. There's a class of errors that is tied to these symbols, 

When I check the list and encounter an error I have to choose a place to highlight - so I need to pick a symbol from this list to point to. I'd like to use something like `list.find(|s| !s.span.is_call_site()).map(|s| s.span()).unwrap_or(Span::call_site())`. Unfortunately, I have no choice but to use `list[0].span()` which may or may not be a `call_site` one. 

I'm not sure if I should have asked this in `proc-macro` repository, feel free to move it where appropriate.

**Comment by dtolnay** [comment]
I don't expect that an API like this would get accepted into libproc_macro, and it's not something that proc-macro2 can provide independently of that.
