### ISSUE TITLE
Document *how to* "Bring proc-macro-like functionality to other contexts"

### ISSUE THREAD

**Issue by Kixunil** [dtolnay/proc-macro2#213]
Currently, the documentations says:

> Bring proc-macro-like functionality to other contexts like build.rs and main.rs.

However, it doesn't explain how to actually do it. I'm interested in this feature, but unsure how to make use of it. I'd like to have a special derive attribute, that works normally in the code, but can be ran outside of the compiler with a bit differet parameters to produce completely different output. Do I have to implement scanning manually or is there already a crate for that?

I have several projects that could use this, one of them being rewriting [`configure_me`](https://github.com/Kixunil/configure_me) to use proc macros instead.

**Comment by eddyb** [comment]
I suspect that "functionality" referred there is the ability to use the `proc_macro` API *at all*, not actually running expansion outside of the compiler (which I haven't heard of since the `syntex` days, and that doesn't account for the module system integration that has happened since).

**Comment by leo60228** [comment]
Proc macros are just functions with a `#[proc_macro]` attribute. If you put a version of the proc macro using `proc_macro2::TokenStream`in its own crate, and make the actual `#[proc_macro]` a wrapper around that function, you can call the proc macro directly wherever you want. Here's an example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3b91e58dc11fd680f17b78b28ef94652

**Comment by Kixunil** [comment]
@leo60228 oh, that's a nice trick, thanks! I think I could even reuse the current code for `configure_me` case.
