### ISSUE TITLE
documentation variants with shifted spans for content

### ISSUE THREAD

**Issue by drahnr** [dtolnay/proc-macro2#244]
Attempting to parse doc comments I find myself in need of various adjustments so the string representation and the actual span length are equiv as well as extracting a span that covers just the literal spans check https://github.com/drahnr/cargo-spellcheck/blob/master/src/documentation/literal.rs#L104-L123 .

While the above is only for ascii due to the len, just adding `"` in a `///` comment breaks the above.

I.e. `/// if a layer is provided a identiacla "input" and "output", it will only be supplied an` would become a rendered literal `"/// if a layer is provided a identiacla \"input\" and \"output\", it will only be supplied an` would"` with a unexpected length and also a wrong (from application pov) span.

How would I extract the correct span for the actual documentation content?

Any help would be highly appreciated.

**Comment by drahnr** [comment]
There are already a bunch of tests in an attempt the correct span https://github.com/drahnr/cargo-spellcheck/blob/master/src/documentation/literal.rs#L302-L591

**Comment by dtolnay** [comment]
The best way would be to use https://docs.rs/proc-macro2/1/proc_macro2/struct.Span.html#method.byte_range.

```rust
// [dependencies]
// proc-macro2 = { version = "1", features = ["span-locations"] }
// syn = { version = "2", features = ["full", "visit"] }

use syn::spanned::Spanned as _;
use syn::visit::Visit as _;
use syn::Attribute;

struct DocCommentVisitor<'a> {
    content: &'a str,
}

impl<'a, 'ast> syn::visit::Visit<'ast> for DocCommentVisitor<'a> {
    fn visit_attribute(&mut self, attr: &'ast Attribute) {
        if attr.path().is_ident("doc") {
            println!("{}", &self.content[attr.span().byte_range()]);
        }
    }
}

/// if a layer is provided a identiacla "input" and "output", it will only be supplied an
fn main() {
    let content = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/", file!()));
    let syntax_tree = syn::parse_file(content).unwrap();
    let mut visitor = DocCommentVisitor { content };
    visitor.visit_file(&syntax_tree);
}
```

```console
/// if a layer is provided a identiacla "input" and "output", it will only be supplied an
```
