### ISSUE TITLE
Consider exposing slicing operation via Span and Range<LineColumn>

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/proc-macro2#269]
These would be sweet:

```rust
impl Index<Span> for str {
    type Output = str;
}

impl Index<Range<LineColumn>> for str {
    type Output = str;
}
```

The latter is forbidden by orphan rules but maybe we can figure something else out.

This allows grabbing whitespace between consecutive tokens, for example to process comments or to implement formatting-preserving code refactoring tools:

```rust
let tokens = input.parse::<TokenStream>()?;
let mut tokens = tokens.into_iter();

let first = tokens.next().unwrap();
println!("{:?}", &input[first.span()]);

let second = tokens.next().unwrap();
let whitespace_between = &input[first.span().end()..second.span().start()];
println!("{:?}", whitespace_between);
```

It's possible to accomplish the same thing using just Span::start and Span::end but requires the user to accurately reimplement [proc-macro2's linecounting](https://github.com/alexcrichton/proc-macro2/blob/3c856d2bd850aef563487a6feece1b8aedeadd4e/src/fallback.rs#L304-L352) to reverse the mapping from byte offsets to line/column pairs.

I don't think libproc_macro would want to expose these operations but it might make sense for proc-macro2 to.

**Comment by mystor** [comment]
Given that when using the `proc_macro` backend, these index operators would require doing potentially expensive line counting to reverse from line/column pairs to byte offsets, perhaps these shouldn't directly use the index operators? I think that `Index` tends to imply a relatively efficient getter when it's seen.

Perhaps `proc-macro2` (or a sibling crate) could expose a `SourceText` type which wraps `&str`, caches the line/column indexes, and provides these index operators, as with a built cache it would be more efficient (especially if doing a lot of accesses).

**Comment by dtolnay** [comment]
`SourceText` as a sibling crate sounds like the ideal path forward here. :+1:
