### ISSUE TITLE
1.0.33 failing builds on docs.rs

### ISSUE THREAD

**Issue by jaskij** [dtolnay/proc-macro2#309]
Just in case you haven't noticed - it's failing.

![image](https://user-images.githubusercontent.com/1429132/146008988-a3bfc9ed-e237-476f-996e-4f4e4d834bfd.png)

Log link for easy access: https://docs.rs/crate/proc-macro2/1.0.33/builds/473000

**Comment by dtolnay** [comment]
Thanks, had not seen.

Looks like this was caused by https://github.com/rust-lang/docs.rs/pull/1543.

**Comment by dtolnay** [comment]
https://docs.rs/proc-macro2/1.0.34
