### ISSUE TITLE
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found

### ISSUE THREAD

**Issue by g-cyan** [dtolnay/proc-macro2#313]
I am a newbie of posting an issue at github.

As I `cargo build --release` , I got the following error.

`error: failed to run custom build command for 'proc-macro2 v1.0.34'`

with the message of `/lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.32' not found`

What can be done first?

**Comment by g-cyan** [comment]
```bash
RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo build --release 
```
This may work.

**Comment by dtolnay** [comment]
I'm not sure, but this does not sound like something that would be related to proc-macro2. We don't do anything platform-specific in this crate, it's just an ordinary pure Rust crate.

**Comment by alice-i-cecile** [comment]
I [ran into a user](https://discord.com/channels/691052431525675048/749335865876021248/1309176670531485696) today with a very similar error:

```
error: failed to run custom build command for `proc-macro2 v1.0.89`

Caused by:
  process didn't exit successfully: `/home/matthias/Documents/Rust/bevy/target/debug/build/proc-macro2-af373eff3cd1001c/build-script-build` (exit status: 1)
  --- stderr
  /home/matthias/Documents/Rust/bevy/target/debug/build/proc-macro2-af373eff3cd1001c/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.39' not found (required by /home/matthias/Documents/Rust/bevy/target/debug/build/proc-macro2-af373eff3cd1001c/build-script-build)
```

I have no idea why it's failing in proc-macro2's build script: it [looks reasonable](https://github.com/dtolnay/proc-macro2/blob/master/build.rs).
