### ISSUE TITLE
Expose proc_macro::Span::source_text

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/proc-macro2#349]
Tracking issue: https://github.com/rust-lang/rust/issues/54725. See also https://github.com/rust-lang/rust/issues/101991.

This will involve `TokenStream`'s `FromStr` impl saving the original source string into https://github.com/dtolnay/proc-macro2/blob/1.0.43/src/fallback.rs#L350, which previously only held the filename and the newline offsets. We'll need to check the performance implications.

**Comment by MingweiSamuel** [comment]
Is checking performance implications the current next step for this?

**Comment by dtolnay** [comment]
It's probably fine.
