### ISSUE TITLE
Convert from proc_macro2::Span to proc_macro::Span without panic

### ISSUE THREAD

**Issue by TedDriggs** [dtolnay/proc-macro2#365]
Right now, it looks like `proc_macro2::Span::unwrap` is the only way to get a `proc_macro::Span`, but that will panic if it's called outside a proc macro. Could there be a `TryFrom`/`TryInto` impl, or a method that returns `Option<proc_macro::Span>`?

**Comment by MingweiSamuel** [comment]
Test

**Comment by dtolnay** [comment]
I think this is supported well enough by `proc_macro::is_available().then(|| span2.unwrap())`.

**Comment by MingweiSamuel** [comment]
For people searching here, you will need to add
```rust
extern crate proc_macro;
```
in order to call `proc_macro::is_available()`
outside of a `proc-maro = true` crate.

The ergonomics of a single method call would be nice
