### ISSUE TITLE
Breaking change in 1.0.52

### ISSUE THREAD

**Issue by SergioBenitez** [dtolnay/proc-macro2#369]
It looks like a patch release contained a breaking change. See https://github.com/SergioBenitez/Rocket/issues/2491.

**Comment by dtolnay** [comment]
This is not in proc-macro2 but in quote, and that quote version was yanked a while ago. See https://github.com/dtolnay/quote/issues/243.

**Comment by SergioBenitez** [comment]
Got it. Apologies, I wasn't able to investigate properly prior to opening this issue. Thanks!
