### ISSUE TITLE
Consider an API to reset thread-local Span data

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/proc-macro2#414]
Basically truncate this thing:

https://github.com/dtolnay/proc-macro2/blob/fecb02df0e2966c7eb39e020dbf650fa8bafd0c5/src/fallback.rs#L323-L325

Resetting would be a claim that all currently existing non-call-site spans on the current thread are no longer in use, or it's okay if methods like `line`/`column` and `source_text` crash or produce wrong results.

A workload that involves parsing all versions of all crates on a thread pool of 64 threads would need this, because otherwise our 32-bit positions would overflow. See https://github.com/dtolnay/proc-macro2/issues/413#issuecomment-1754216797.

**Comment by buchgr** [comment]
Adding such an API would be much appreciated. My workload is similar to what you described in your comment. David, did you already have an API in mind? I'd be happy to file a PR.

Also for my understanding: The idea behind the thread-local source map is to avoid a ref on Span and safe bytes?

**Comment by dtolnay** [comment]
Something like `proc_macro2::invalidate_current_thread_spans()` with a realistic code example.

> The idea behind the thread-local source map is to avoid a ref on Span to safe bytes?

`Span` needs to be Copy and 'static. I don't know any other way to implement that, regardless of how many bytes big Span is.
