### ISSUE TITLE
Build script fails when compiling with target-feature=+avx512bw

### ISSUE THREAD

**Issue by tuzz** [dtolnay/proc-macro2#426]
I am trying to build an executable that has AVX-512 support. The machine I am building it on does not support AVX-512 but the machine the executable will be deployed to does. I am receiving the following build error:

```
error: failed to run custom build command for `proc-macro2 v1.0.70`

Caused by:
  process didn't exit successfully: `/foo/target/release/build/proc-macro2-89d6587599e0b3b6/build-script-build` (signal: 4, SIGILL: illegal instruction)
  --- stdout
  cargo:rerun-if-changed=build.rs
```

To reproduce this problem, you need to compile on an x64_64 machine that does not support AVX-512 natively. You can confirm this by running `cat /proc/cpuinfo | grep avx512` and checking that nothing is returned.

Then, create a Cargo.toml with the following:

```toml
[package]
name = "minimal-reproduction"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "*"
```

Then, compile the crate with the following:

```sh
RUSTFLAGS="-C target-feature=+avx512bw" cargo build
```

I have tried setting the `--cfg procmacro2_semver_exempt` flag which did not seem to help.

Does anyone know what's going on? Thanks

**Comment by dtolnay** [comment]
`RUSTFLAGS` is applied to the compilation of both target code **and** build scripts when Cargo is not in cross-compile mode.

Your command makes build.rs crash on this line:

https://github.com/dtolnay/proc-macro2/blob/49b26d2d7703f46f4fd1d3baea2c2e3b177a8afb/build.rs#L95

If I add `return None;` above that line, it does not crash. If I add it on the next line, it crashes.

Based on `RUSTFLAGS="-C target-feature=+avx512bw" cargo build --verbose`, the build script itself is compiled with `+avx512bw` by Cargo, so a crash makes sense as soon as it hits an instruction that is not available in the host CPU.

```console
Running `~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name build_scrip
  t_build --edition=2021 ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.7
  0/build.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diag
    ^^^^^^^^
  nostic-width=118 --crate-type bin --emit=dep-info,link -C embed-bitcode=no --cfg 'feature="defa
  ult"' --cfg 'feature="proc-macro"' -C metadata=5c68bf8a9ae873e5 -C extra-filename=-5c68bf8a9ae8
  73e5 --out-dir target/debug/build/proc-macro2-5c68bf8a9ae873e5 -C incremental=target/debug/incr
  emental -L dependency=target/debug/deps -C target-feature=+avx512bw`
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

You need to put Cargo in cross-compiling mode in order for it to pass different rustflags to host vs target builds, by passing `--target`. The correct syntax is:

```console
$ cargo build --target x86_64-unknown-linux-gnu --config 'target.x86_64-unknown-linux-gnu.rustflags=["-C", "target_feature=+avx512bw"]'
```

or:

```console
$ RUSTFLAGS='-C target-feature=+avx512bw' cargo build --target x86_64-unknown-linux-gnu
```

This is effective even if the host and target happen to be the same target triple.

**Comment by tuzz** [comment]
Ahh, thank you.

In my particular case, I had misunderstood how to do runtime detection of SIMD features. I needed to add `#[target_feature(enable = "...")]` to regions of code that used SIMD features. [This guide](https://rust-lang.github.io/rfcs/2045-target-feature.html) was very helpful.

Closing now. Thanks again.
