### ISSUE TITLE
Help with debugging build command error

### ISSUE THREAD

**Issue by mo8it** [dtolnay/proc-macro2#454]
Hello,

I got [this issue](https://github.com/rust-lang/rustlings/issues/1953) on the Rustlings repo and I can't reproduce it and have no idea how to debug it because of the custom build command. Do you have an idea of why the compilation fails or how to debug it?

Summary: `proc-macro2` fails to run the custom build command in the release profile (not in debug) on MacOS.

Thank you  ❤️

**Comment by dtolnay** [comment]
Looks like https://github.com/rust-lang/cargo/issues/8913.
