### ISSUE TITLE
Tokenize text with unbalanced delimiters

### ISSUE THREAD

**Issue by smoelius** [dtolnay/proc-macro2#459]
Can `proc-macro2` be used to tokenize text with unbalanced delimiters? If so, could you please point me to what in the crate I should use?

I am trying to tokenize text like this:
```rust
&& let reason = match (is_send, is_sync) {
```
However, as the docs indicate, attempting to do so with [`TokenStream::from_str`](https://docs.rs/proc-macro2/latest/proc_macro2/struct.TokenStream.html#impl-FromStr-for-TokenStream) fails:
```rust
called `Result::unwrap()` on an `Err` value: LexError { span: bytes(42..42) }
```
([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f47b4c83ed17241711fdbf266e778814))

For context, the text is coming from `git` diffs.

**Comment by dtolnay** [comment]
This is not supported by this crate. You are going to need different data structures for that kind of input.

**Comment by smoelius** [comment]
Thanks very much for your response.
