### ISSUE TITLE
Allow for lexing of non-doc comments

### ISSUE THREAD

**Issue by Qix-** [dtolnay/proc-macro2#468]
Normally a lexer (rightfully) excludes non-doc comments but I have a particular usecase where having the opt-in ability to lex normal comments would be appreciated.

In a safety-critical project I'd like to write a lint pass whereby all instances of `unsafe {}` blocks are commented with a `// SAFETY` comment explaining the use of the unsafe block in order to enforce this documentation. It's a convention in the codebase already but it's something I'd like to make sure is enforceable via CI.

I could fork proc-macro2 to add this of course but I wanted to see if this was something upstream would be interested in having, or at least to see if there was maybe a better way of going about doing this - especially since having the feature enabled would break `syn` parsing unless it was patched to ignore comment tokens.

Would the better approach just be to allow the "useless doc comment" lint and instead enforce that statements with unsafe blocks have a `#[doc]` attribute?

Thanks for any info!

**Comment by phR0ze** [comment]
Definitely an interesting idea in my opinion. I'd love to see proc-macro2 and syn both updated to support regular comments. This would open up some nice use cases with pretty-print as well.

**Comment by dtolnay** [comment]
This is already supported by inspecting the input string between consecutive tokens.

```rust
// [dependencies]
// proc-macro2 = { version = "1", features = ["span-locations"] }
// syn = { version = "2", features = ["full", "visit"] }

use core::num::NonZero;
use core::ops::Range;
use core::str::FromStr;
use proc_macro2::{TokenStream, TokenTree};
use syn::visit::Visit as _;
use syn::ExprUnsafe;

pub fn example(n: usize) -> NonZero<usize> {
    if n == 0 {
        panic!();
    }
    // SAFETY: n != 0
    unsafe { NonZero::new_unchecked(n) }
}

fn collect_ranges(tokens: TokenStream, token_ranges: &mut Vec<Range<usize>>) {
    for token in tokens {
        if let TokenTree::Group(group) = token {
            let range = group.span().byte_range();
            token_ranges.push(Range { start: range.start, end: range.start + 1 });
            collect_ranges(group.stream(), token_ranges);
            token_ranges.push(Range { start: range.end - 1, end: range.end });
        } else {
            token_ranges.push(token.span().byte_range());
        }
    }
}

struct SafetyCommentVisitor<'a> {
    content: &'a str,
    token_ranges: &'a [Range<usize>],
}

impl<'a, 'ast> syn::visit::Visit<'ast> for SafetyCommentVisitor<'a> {
    fn visit_expr_unsafe(&mut self, expr: &'ast ExprUnsafe) {
        let range = expr.unsafe_token.span.byte_range();
        let index = self
            .token_ranges
            .binary_search_by(|other| other.start.cmp(&range.start))
            .unwrap();
        let whitespace = &self.content[self.token_ranges[index - 1].end..range.start];
        println!("{:?}", whitespace);
    }
}

fn main() {
    let content = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/", file!()));
    let tokens = TokenStream::from_str(content).unwrap();

    let token_ranges = &mut Vec::new();
    collect_ranges(tokens.clone(), token_ranges);

    let syntax_tree: syn::File = syn::parse2(tokens).unwrap();
    let mut visitor = SafetyCommentVisitor { content, token_ranges };
    visitor.visit_file(&syntax_tree);
}
```

**Comment by Qix-** [comment]
oh nice, thanks!
