### ISSUE TITLE
release 1.0.90 regression from 1.0.89: wit-bindgen panicking

### ISSUE THREAD

**Issue by pchickey** [dtolnay/proc-macro2#483]
wit-bindgen takes a dependency on `syn = { version = "2.0", features = ["printing"] }`.

In projects with unlocked deps, this macro is panicking when compiled with latest patch release of syn, and with it proc-macro2 1.0.90. It shows the message
`= help: message: compiler/fallback mismatch #949` which I believe is coming from `src/wrapper.rs:48` in this package, and therefore `set_span`.

For an example of the failure https://github.com/yoshuawuyts/wstd/actions/runs/11946511007/job/33301083203?pr=22#step:4:535

Earlier today same packages built with proc-macro2 1.0.89 https://github.com/yoshuawuyts/wstd/actions/runs/11940671307/job/33283840092#step:4:151

Unfortunately I don't understand the internals of this crate enough to diagnose further. Is this my issue, or a bug in the latest proc-macro2 release?

**Comment by sehz** [comment]
All our project builds are now failing due to this.  We rely on `wit-bindgen`.

**Comment by sehz** [comment]
@dtolnay, is possible to revert changes and do another release?

**Comment by dtolnay** [comment]
This is fixed in 1.0.91.

**Comment by sehz** [comment]
Confirm fixed works.  Thanks!

**Comment by pchickey** [comment]
Thanks for the quick fix!
