### ISSUE TITLE
IntoIterator for &TokenStream

### ISSUE THREAD

**Issue by xd009642** [dtolnay/proc-macro2#88]
I found when using `TokenStream` I couldn't iterate over a `&TokenStream` because `IntoIterator` wasn't implemented for it. Is there a reason this isn't included? If not I can submit a PR for this and any similar things in the same area with the same issue.

**Comment by alexcrichton** [comment]
I think it's mostly just left out at the moment to be conservative, but given that it's intended to be cheap to clone I think this'd probably be a fine addition to have. This may wish to be added to upstream rust-lang/rust first though and then we can mirror it down here.

**Comment by xd009642** [comment]
Okie dokie, I'll look into implementing it on the compiler first and doing a PR. I'll also run the benchmarks to see if there are any actual gains to be had given it's a cheap clone.

**Comment by dtolnay** [comment]
This API isn't in libproc_macro so I don't think we need to keep an issue here about it.
